[workspace]

resolver = "2"

members = [
    "crates/relayer",
    "crates/relayer-types",
    "crates/relayer-cli",
    "crates/relayer-rest",
    "crates/relayer-components",
    "crates/relayer-components-extra",
    "crates/relayer-all-in-one",
    "crates/relayer-mock",
    "crates/relayer-runtime",
    "crates/relayer-cosmos",
    "crates/relayer-cosmos-mock",
    "crates/telemetry",
    "crates/chain-registry",
    "tools/integration-test",
    "tools/test-framework",
]

exclude = [
    "tools/check-guide",
    "tools/query-events",
]

[profile.release]
overflow-checks = true

[patch.crates-io]
tendermint = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "farhad/testgen-app-hash" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "farhad/testgen-app-hash" }
tendermint-testgen = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "farhad/testgen-app-hash" }