[workspace]

resolver = "2"

members = [
    "crates/relayer",
    "crates/relayer-types",
    "crates/relayer-cli",
    "crates/relayer-rest",
    "crates/telemetry",
    "crates/chain-registry",
    "tools/integration-test",
    "tools/test-framework",
]

exclude = [
    "tools/check-guide",
    "tools/query-events",
]

[profile.release]
overflow-checks = true

[patch.crates-io]
# tendermint                       = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
# tendermint-rpc                   = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
# tendermint-proto                 = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
# tendermint-light-client          = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
# tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
# tendermint-light-client-detector = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
# tendermint-testgen               = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "main" }
tendermint                       = { path = "<PATH TO UPDATED TENDERMINT-RS>/tendermint" }
tendermint-rpc                   = { path = "<PATH TO UPDATED TENDERMINT-RS>/rpc" }
tendermint-proto                 = { path = "<PATH TO UPDATED TENDERMINT-RS>/proto" }
tendermint-light-client          = { path = "<PATH TO UPDATED TENDERMINT-RS>/light-client" }
tendermint-light-client-verifier = { path = "<PATH TO UPDATED TENDERMINT-RS>/light-client-verifier" }
tendermint-light-client-detector = { path = "<PATH TO UPDATED TENDERMINT-RS>/light-client-detector" }
tendermint-testgen               = { path = "<PATH TO UPDATED TENDERMINT-RS>/testgen" }
ibc-proto                        = { path = "<PATH TO UPDATED IBC-PROTO-RS>" }